/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#380c00",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "tertiary-container": "#c5a018",
        "on-secondary-fixed": "#00201d",
        "inverse-surface": "#303030",
        "error": "#ba1a1a",
        "primary": "#a43c12",
        "surface-container-low": "#f5f3f3",
        "surface-container-highest": "#e4e2e1",
        "on-secondary-container": "#006f67",
        "error-container": "#ffdad6",
        "surface-container": "#f0eded",
        "on-surface": "#1b1c1c",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffe087",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#71d7cd",
        "background": "#fbf9f8",
        "outline": "#8b7169",
        "surface-variant": "#e4e2e1",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ebc23e",
        "inverse-on-surface": "#f2f0f0",
        "secondary-container": "#8bf1e6",
        "primary-fixed": "#ffdbcf",
        "surface-container-high": "#eae8e7",
        "on-background": "#1b1c1c",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#00504a",
        "inverse-primary": "#ffb59c",
        "primary-container": "#ff7f50",
        "on-tertiary-container": "#483800",
        "surface-tint": "#a43c12",
        "secondary-fixed": "#8ef4e9",
        "on-primary-fixed-variant": "#822800",
        "tertiary": "#735c00",
        "outline-variant": "#dec0b6",
        "on-tertiary-fixed-variant": "#574500",
        "surface-bright": "#fbf9f8",
        "surface": "#fbf9f8",
        "on-primary-container": "#6c2000",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#57423b",
        "on-tertiary-fixed": "#241a00",
        "primary-fixed-dim": "#ffb59c",
        "secondary": "#006a63",
        "cream": "#FFFBF5",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        lg: "40px",
        sm: "12px",
        gutter: "24px",
        xl: "64px",
        xs: "4px",
        base: "8px",
        "container-max": "1920px",
        md: "24px",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "title-lg": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        "card": "0px 4px 20px rgba(255, 127, 80, 0.08)",
        "card-hover": "0px 8px 30px rgba(255, 127, 80, 0.15)",
        "nav": "0px -4px 20px rgba(255, 127, 80, 0.08)",
      },
      keyframes: {
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "bounce-slow": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
      },
      animation: {
        "float": "float 3s ease-in-out infinite",
        "bounce-slow": "bounce-slow 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
